---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: yes
configure_terminal: yes
configure_osx: yes

dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .zshrc
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  - autoconf
  - bash-completion
  - git
  - github/gh/gh
  - go
  - gpg
  - httpie
  - iperf
  - sqlite
  - nmap
  - ssh-copy-id
  - cowsay
  - readline
  - openssl
  - pv
  - wget
  - terraform
  - archey
  - helm
  - htop
  - gnu-tar
  - packer
  - zsh
  - terragrunt

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - chromedriver
  - docker
  - firefox
  - google-chrome
  - licecap
  - sequel-pro
  - slack
  - evernote
  - transmit
  - vagrant
  - visual-studio-code
  - google-cloud-sdk
  - iterm2

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 443987910, name: "1Password" }
mas_email: "{{ username }}"
mas_password: "{{ password }}"

osx_script: "~/.osx --no-restart"
